### ISSUE TITLE
core_cm3.c needs to be fixed

### ISSUE THREAD

**Issue by dalbert2** [karlp/kkstm32_base#1]
The STM32 library contains an error in core_cm3.c that must be fixed (add the ‘&’ in front of result r); see diffs below:

dalbert@mypc ~/NetBeansProjects/kkstm32_base-master/libs_stm/inc/core_support $ diff core_cm3.c.orig core_cm3.c
736c736
<    __ASM volatile (“strexb %0, %2, [%1]” : “=r” (result) : “r” (addr), “r” (value) );
—

>    __ASM volatile (“strexb %0, %2, [%1]” : “=&r” (result) : “r” (addr), “r” (value) );
> 753c753
> <    __ASM volatile (“strexh %0, %2, [%1]” : “=r” (result) : “r” (addr), “r” (value) );
> —
>    __ASM volatile (“strexh %0, %2, [%1]” : “=&r” (result) : “r” (addr), “r” (value) );

**Comment by karlp** [comment]
True.  Long long fixed in other sources.  I don't use or maintain this blob of code.  I don't recommend using this code for anything, I've only left it so as not to break any links.  Very little of this is still relevant.
